//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Scraper.ScraperProvincial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScraperProvincialResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScraperProvincialResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Scraper.ScraperProvincial.ScraperProvincialResources", typeof(ScraperProvincialResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CharDash {
            get {
                return ResourceManager.GetString("CharDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string CharSlash {
            get {
                return ResourceManager.GetString("CharSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CMNBack {
            get {
                return ResourceManager.GetString("CMNBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string CMNForward {
            get {
                return ResourceManager.GetString("CMNForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string CMNReload {
            get {
                return ResourceManager.GetString("CMNReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string HtmlAttributeValue {
            get {
                return ResourceManager.GetString("HtmlAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-right.
        /// </summary>
        public static string HtmlIDContentRight {
            get {
                return ResourceManager.GetString("HtmlIDContentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuentasPersonales.
        /// </summary>
        public static string HtmlIDCuentas {
            get {
                return ResourceManager.GetString("HtmlIDCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tfLISBUSCADORFECFIN.
        /// </summary>
        public static string HtmlIDFechaFin {
            get {
                return ResourceManager.GetString("HtmlIDFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tfLISBUSCADORFECINCIO.
        /// </summary>
        public static string HtmlIDFechaInicio {
            get {
                return ResourceManager.GetString("HtmlIDFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtros.
        /// </summary>
        public static string HtmlIDFiltros {
            get {
                return ResourceManager.GetString("HtmlIDFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regresarListado.
        /// </summary>
        public static string HtmlIDListado {
            get {
                return ResourceManager.GetString("HtmlIDListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod_cvepass.
        /// </summary>
        public static string HtmlIDLoginClave {
            get {
                return ResourceManager.GetString("HtmlIDLoginClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingresarLogin.
        /// </summary>
        public static string HtmlIDLoginEntrar {
            get {
                return ResourceManager.GetString("HtmlIDLoginEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD_USU.
        /// </summary>
        public static string HtmlIDLoginUsuario {
            get {
                return ResourceManager.GetString("HtmlIDLoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMIDER.
        /// </summary>
        public static string HtmlIDRifID {
            get {
                return ResourceManager.GetString("HtmlIDRifID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMDOCR.
        /// </summary>
        public static string HtmlIDRifNum {
            get {
                return ResourceManager.GetString("HtmlIDRifNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCTARJ.
        /// </summary>
        public static string HtmlIDTipoDoc {
            get {
                return ResourceManager.GetString("HtmlIDTipoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACIDOC.
        /// </summary>
        public static string HtmlIDTipoRif {
            get {
                return ResourceManager.GetString("HtmlIDTipoRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string HtmlMemberClick {
            get {
                return ResourceManager.GetString("HtmlMemberClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuentasNav.
        /// </summary>
        public static string HtmlNameCuentas {
            get {
                return ResourceManager.GetString("HtmlNameCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnDescargar.
        /// </summary>
        public static string HtmlNameDescargar {
            get {
                return ResourceManager.GetString("HtmlNameDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCabecera.
        /// </summary>
        public static string HtmlNameFrameCabecera {
            get {
                return ResourceManager.GetString("HtmlNameFrameCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fprincipal.
        /// </summary>
        public static string HtmlNameFramePrincipal {
            get {
                return ResourceManager.GetString("HtmlNameFramePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onchange.
        /// </summary>
        public static string HtmlOnchangeEvent {
            get {
                return ResourceManager.GetString("HtmlOnchangeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string HtmlSelectedValue {
            get {
                return ResourceManager.GetString("HtmlSelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        public static string HtmlTagInput {
            get {
                return ResourceManager.GetString("HtmlTagInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string HtmlTagLink {
            get {
                return ResourceManager.GetString("HtmlTagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string NavigateAccount {
            get {
                return ResourceManager.GetString("NavigateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Explorer.
        /// </summary>
        public static string PageTitleDefault {
            get {
                return ResourceManager.GetString("PageTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPasswordProvincial.
        /// </summary>
        public static string SettingsLoginPasswordProvincial {
            get {
                return ResourceManager.GetString("SettingsLoginPasswordProvincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUserProvincial.
        /// </summary>
        public static string SettingsLoginUserProvincial {
            get {
                return ResourceManager.GetString("SettingsLoginUserProvincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string ShortDateFormat {
            get {
                return ResourceManager.GetString("ShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string ToggleDateOptionDay {
            get {
                return ResourceManager.GetString("ToggleDateOptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ToggleDateOptionRange {
            get {
                return ResourceManager.GetString("ToggleDateOptionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vhxp_ve_web/servlet/ServletOperacionWeb.
        /// </summary>
        public static string URLAbsolutePath {
            get {
                return ResourceManager.GetString("URLAbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ve1.provinet.net/nhvp_ve_web/atpn_es_web_jsp/login.jsp?it=2.
        /// </summary>
        public static string URLLogin {
            get {
                return ResourceManager.GetString("URLLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ve1.provinet.net/shvp_ve_web/atpn_es_web_jsp/portal.jsp.
        /// </summary>
        public static string URLLogin2 {
            get {
                return ResourceManager.GetString("URLLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ve1.provinet.net/shvp_ve_web/atpn_es_web_jsp/desconectar.jsp.
        /// </summary>
        public static string URLSalir {
            get {
                return ResourceManager.GetString("URLSalir", resourceCulture);
            }
        }
    }
}
