//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEGENDSERVERII;Initial Catalog=InstaTransfer_Development;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string InstaTransfer_DevelopmentConnectionString {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEGENDSERVERII;Initial Catalog=InstaTransfer_Development;Persist Secu" +
            "rity Info=True;User ID=sa;Password=legendsoft$$11")]
        public string ITConnectionString {
            get {
                return ((string)(this["ITConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-J2PB;Initial Catalog=InstaTransfer_Development;Integrated Security" +
            "=True")]
        public string InstaTransfer_DevelopmentConnectionString1 {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEGENDSERVERII;Initial Catalog=InstaTransfer_Source;Persist Security " +
            "Info=True;User ID=sa;Password=legendsoft$$11")]
        public string InstaTransfer_SourceConnectionString {
            get {
                return ((string)(this["InstaTransfer_SourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=legendserverii;Initial Catalog=InstaTransfer_Development;User ID=sa;P" +
            "assword=legendsoft$$11")]
        public string InstaTransfer_DevelopmentConnectionString2 {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=InstaTransfer_Development;User I" +
            "D=sa;Password=MAMALOnojoda$$11")]
        public string InstaTransfer_DevelopmentConnectionString3 {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=InstaTransfer_Development;Persis" +
            "t Security Info=True;User ID=sa;Password=MAMALOnojoda$$11")]
        public string InstaTransfer_DevelopmentConnectionString4 {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Initial Catalog=InstaTransfer_Development;User I" +
            "D=sa;Password=MAMALOnojoda$$11")]
        public string InstaTransfer_DevelopmentConnectionString5 {
            get {
                return ((string)(this["InstaTransfer_DevelopmentConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=InstaTransfer;Persist Security I" +
            "nfo=True;User ID=sa;Password=MAMALOnojoda$$11")]
        public string InstaTransferConnectionString {
            get {
                return ((string)(this["InstaTransferConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=108.168.173.11;Initial Catalog=InstaTransfer_Source;Persist Security " +
            "Info=True;User ID=sa;Password=^x2@sg`]RR(S`&bs")]
        public string InstaTransfer_SourceConnectionString1 {
            get {
                return ((string)(this["InstaTransfer_SourceConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\legendinstance;Initial Catalog=InstaTransfer_Source;Per" +
            "sist Security Info=True;User ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_SourceConnectionString2 {
            get {
                return ((string)(this["InstaTransfer_SourceConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=InstaTransfer_Source;Per" +
            "sist Security Info=True;User ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_SourceConnectionString3 {
            get {
                return ((string)(this["InstaTransfer_SourceConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=EmprestaII;User ID=dbate" +
            "ch;Password=migracion$$11")]
        public string EmprestaIIConnectionString {
            get {
                return ((string)(this["EmprestaIIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=InstaTransfer_Source_Tes" +
            "t;User ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_Source_TestConnectionString {
            get {
                return ((string)(this["InstaTransfer_Source_TestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=InstaTransfer_SourceTest" +
            ";Persist Security Info=True;User ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_SourceTestConnectionString {
            get {
                return ((string)(this["InstaTransfer_SourceTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=InstaTransfer_Source;Use" +
            "r ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_SourceConnectionString4 {
            get {
                return ((string)(this["InstaTransfer_SourceConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.54.211.86\\LEGENDINSTANCE;Initial Catalog=InstaTransfer_SourceTest" +
            ";User ID=dbatech;Password=migracion$$11")]
        public string InstaTransfer_SourceTestConnectionString1 {
            get {
                return ((string)(this["InstaTransfer_SourceTestConnectionString1"]));
            }
        }
    }
}
