//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.General.GeneralErrors", typeof(GeneralErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-009.
        /// </summary>
        public static string ArgumentExceptionCode {
            get {
                return ResourceManager.GetString("ArgumentExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en argumento.
        /// </summary>
        public static string ArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-006.
        /// </summary>
        public static string ArgumentNullExceptionCode {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento nulo.
        /// </summary>
        public static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-011.
        /// </summary>
        public static string FiddlerExceptionCode {
            get {
                return ResourceManager.GetString("FiddlerExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede inicializar fiddler.
        /// </summary>
        public static string FiddlerExceptionMessage {
            get {
                return ResourceManager.GetString("FiddlerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-002.
        /// </summary>
        public static string FormatExceptionCode {
            get {
                return ResourceManager.GetString("FormatExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El string de entrada no esta en el formato correcto.
        /// </summary>
        public static string FormatExceptionMessage {
            get {
                return ResourceManager.GetString("FormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-003.
        /// </summary>
        public static string IndexOutOfRangeExceptionCode {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de parámetros de entrada es incorrecto o no existente.
        /// </summary>
        public static string IndexOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-001.
        /// </summary>
        public static string IOExceptionCode {
            get {
                return ResourceManager.GetString("IOExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta de la red no fue encontrada.
        /// </summary>
        public static string IOExceptionMessage {
            get {
                return ResourceManager.GetString("IOExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-010.
        /// </summary>
        public static string NoInternetConnectionExceptionCode {
            get {
                return ResourceManager.GetString("NoInternetConnectionExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conexion de internet.
        /// </summary>
        public static string NoInternetConnectionExceptionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-005.
        /// </summary>
        public static string NotSupportedExceptionCode {
            get {
                return ResourceManager.GetString("NotSupportedExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta dada no es compatible.
        /// </summary>
        public static string NotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("NotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-004.
        /// </summary>
        public static string NullReferenceExceptionCode {
            get {
                return ResourceManager.GetString("NullReferenceExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia nula.
        /// </summary>
        public static string NullReferenceExceptionMessage {
            get {
                return ResourceManager.GetString("NullReferenceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-000.
        /// </summary>
        public static string SystemErrorCode {
            get {
                return ResourceManager.GetString("SystemErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de sistema.
        /// </summary>
        public static string SystemErrorMessage {
            get {
                return ResourceManager.GetString("SystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-007.
        /// </summary>
        public static string UnauthorizedAccessExceptionCode {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso no autorizado.
        /// </summary>
        public static string UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-012.
        /// </summary>
        public static string UserLoginExceptionCode {
            get {
                return ResourceManager.GetString("UserLoginExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de inicio de sesion.
        /// </summary>
        public static string UserLoginExceptionMessage {
            get {
                return ResourceManager.GetString("UserLoginExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-008.
        /// </summary>
        public static string UserNotFoundExceptionCode {
            get {
                return ResourceManager.GetString("UserNotFoundExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de plataforma en linea no encontrado.
        /// </summary>
        public static string UserNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("UserNotFoundExceptionMessage", resourceCulture);
            }
        }
    }
}
