//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.General.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\UmbrellaServices\app.config.
        /// </summary>
        public static string AppConfigPath {
            get {
                return ResourceManager.GetString("AppConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupPath.
        /// </summary>
        public static string AppSettingsKeyBackupPath {
            get {
                return ResourceManager.GetString("AppSettingsKeyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasePath.
        /// </summary>
        public static string AppSettingsKeyBasePath {
            get {
                return ResourceManager.GetString("AppSettingsKeyBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultCulture.
        /// </summary>
        public static string AppSettingsKeyDefaultCulture {
            get {
                return ResourceManager.GetString("AppSettingsKeyDefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoReplyTransax.
        /// </summary>
        public static string AppSettingsKeyNoReplyTransax {
            get {
                return ResourceManager.GetString("AppSettingsKeyNoReplyTransax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReconciliatorTime.
        /// </summary>
        public static string AppSettingsKeyReconciliatorTime {
            get {
                return ResourceManager.GetString("AppSettingsKeyReconciliatorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScraperFileName.
        /// </summary>
        public static string AppSettingsKeyScraperFileName {
            get {
                return ResourceManager.GetString("AppSettingsKeyScraperFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScraperTime.
        /// </summary>
        public static string AppSettingsKeyScraperTime {
            get {
                return ResourceManager.GetString("AppSettingsKeyScraperTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScraperTimeout.
        /// </summary>
        public static string AppSettingsKeyScraperTimeout {
            get {
                return ResourceManager.GetString("AppSettingsKeyScraperTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTransax.
        /// </summary>
        public static string AppSettingsKeySupportTransax {
            get {
                return ResourceManager.GetString("AppSettingsKeySupportTransax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterFileName.
        /// </summary>
        public static string AppSettingsKeyUpdaterFileName {
            get {
                return ResourceManager.GetString("AppSettingsKeyUpdaterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterTime.
        /// </summary>
        public static string AppSettingsKeyUpdaterTime {
            get {
                return ResourceManager.GetString("AppSettingsKeyUpdaterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITConnectionString.
        /// </summary>
        public static string ConnectionStringKey {
            get {
                return ResourceManager.GetString("ConnectionStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank.
        /// </summary>
        public static string DictionaryKeyBank {
            get {
                return ResourceManager.GetString("DictionaryKeyBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string DictionaryKeyFilePath {
            get {
                return ResourceManager.GetString("DictionaryKeyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socialReason.
        /// </summary>
        public static string DictionaryKeySocialReason {
            get {
                return ResourceManager.GetString("DictionaryKeySocialReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string DictionaryKeyUsername {
            get {
                return ResourceManager.GetString("DictionaryKeyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userStatus.
        /// </summary>
        public static string DictionaryKeyUserStatus {
            get {
                return ResourceManager.GetString("DictionaryKeyUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [msdb]
        ///GO
        ///
        ////****** Object:  Job [UUser_Unlocker]    Script Date: 6/4/2017 9:42:43 a. m. ******/
        ///BEGIN TRANSACTION
        ///DECLARE @ReturnCode INT
        ///SELECT @ReturnCode = 0
        ////****** Object:  JobCategory [[Uncategorized (Local)]]    Script Date: 6/4/2017 9:42:43 a. m. ******/
        ///IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N&apos;[Uncategorized (Local)]&apos; AND category_class=1)
        ///BEGIN
        ///EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N&apos;JOB&apos;, @type=N&apos;LOCAL&apos;, @name=N&apos;[Uncategorized (Local)]&apos;
        ///IF (@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JobUnlockUser {
            get {
                return ResourceManager.GetString("JobUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Log.
        /// </summary>
        public static string LogNameUmbrella {
            get {
                return ResourceManager.GetString("LogNameUmbrella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        public static string SemiColon {
            get {
                return ResourceManager.GetString("SemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yy.
        /// </summary>
        public static string ShortDateFormat {
            get {
                return ResourceManager.GetString("ShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Program.
        /// </summary>
        public static string SourceNameUmbrella {
            get {
                return ResourceManager.GetString("SourceNameUmbrella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Reconciliator.
        /// </summary>
        public static string SourceNameUmbrellaReconciliator {
            get {
                return ResourceManager.GetString("SourceNameUmbrellaReconciliator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Scraper.
        /// </summary>
        public static string SourceNameUmbrellaScraper {
            get {
                return ResourceManager.GetString("SourceNameUmbrellaScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Updater.
        /// </summary>
        public static string SourceNameUmbrellaUpdater {
            get {
                return ResourceManager.GetString("SourceNameUmbrellaUpdater", resourceCulture);
            }
        }
    }
}
