//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Updater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdaterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Updater.UpdaterResources", typeof(UpdaterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterBanescoFiltersInclude.
        /// </summary>
        public static string AppSettingsKeyUpdaterBanescoFiltersInclude {
            get {
                return ResourceManager.GetString("AppSettingsKeyUpdaterBanescoFiltersInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterFiltersExclude.
        /// </summary>
        public static string AppSettingsKeyUpdaterFiltersExclude {
            get {
                return ResourceManager.GetString("AppSettingsKeyUpdaterFiltersExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string CleanValueDate {
            get {
                return ResourceManager.GetString("CleanValueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotes.
        /// </summary>
        public static string CleanValueQuotes {
            get {
                return ResourceManager.GetString("CleanValueQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backupPath.
        /// </summary>
        public static string DictionaryKeyBackupPath {
            get {
                return ResourceManager.GetString("DictionaryKeyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank.
        /// </summary>
        public static string DictionaryKeyBank {
            get {
                return ResourceManager.GetString("DictionaryKeyBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bankStatement.
        /// </summary>
        public static string DictionaryKeyBankStatement {
            get {
                return ResourceManager.GetString("DictionaryKeyBankStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileName.
        /// </summary>
        public static string DictionaryKeyFileName {
            get {
                return ResourceManager.GetString("DictionaryKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullPath.
        /// </summary>
        public static string DictionaryKeyFullPath {
            get {
                return ResourceManager.GetString("DictionaryKeyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        public static string DictionaryKeyPath {
            get {
                return ResourceManager.GetString("DictionaryKeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statementDate.
        /// </summary>
        public static string DictionaryKeyStatementDate {
            get {
                return ResourceManager.GetString("DictionaryKeyStatementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d/MM/yyyy.
        /// </summary>
        public static string ShortDateFormat {
            get {
                return ResourceManager.GetString("ShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANS.CTAS.
        /// </summary>
        public static string TransferDescriptionBanesco {
            get {
                return ResourceManager.GetString("TransferDescriptionBanesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANS.CTAS A TERCERO EN BANESCO.
        /// </summary>
        public static string TransferThirdsDesctiptionBanesco {
            get {
                return ResourceManager.GetString("TransferThirdsDesctiptionBanesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterView.exe.
        /// </summary>
        public static string UpdaterExeName {
            get {
                return ResourceManager.GetString("UpdaterExeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterView.
        /// </summary>
        public static string UpdaterName {
            get {
                return ResourceManager.GetString("UpdaterName", resourceCulture);
            }
        }
    }
}
