//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Scraper.ScraperBanescoPE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScraperBanescoPEResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScraperBanescoPEResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Scraper.ScraperBanescoPE.ScraperBanescoPEResources", typeof(ScraperBanescoPEResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasePath.
        /// </summary>
        public static string AppSettingsKeyBasePath {
            get {
                return ResourceManager.GetString("AppSettingsKeyBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpChargeAccount.
        /// </summary>
        public static string AppSettingsKeyFtpChargeAccount {
            get {
                return ResourceManager.GetString("AppSettingsKeyFtpChargeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpChargeAccountPass.
        /// </summary>
        public static string AppSettingsKeyFtpChargeAccountPass {
            get {
                return ResourceManager.GetString("AppSettingsKeyFtpChargeAccountPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpChargeAccountUser.
        /// </summary>
        public static string AppSettingsKeyFtpChargeAccountUser {
            get {
                return ResourceManager.GetString("AppSettingsKeyFtpChargeAccountUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSmsUrl.
        /// </summary>
        public static string AppSettingsKeyGetSmsUrl {
            get {
                return ResourceManager.GetString("AppSettingsKeyGetSmsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmsFailureMailTo.
        /// </summary>
        public static string AppSettingsKeySmsFailureMailTo {
            get {
                return ResourceManager.GetString("AppSettingsKeySmsFailureMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoReplyTransax.
        /// </summary>
        public static string AppSettingsKeyTransaxNoReplyMail {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxNoReplyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTransax.
        /// </summary>
        public static string AppSettingsKeyTransaxSupportMail {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxSupportMail", resourceCulture);
            }
        }
    }
}
