//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Scraper.ScraperBanesco {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScraperBanescoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScraperBanescoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Scraper.ScraperBanesco.ScraperBanescoResources", typeof(ScraperBanescoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_btnOk.
        /// </summary>
        public static string HtmlIDAceptarExportar {
            get {
                return ResourceManager.GetString("HtmlIDAceptarExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-right.
        /// </summary>
        public static string HtmlIDContentRight {
            get {
                return ResourceManager.GetString("HtmlIDContentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_optDelimitador.
        /// </summary>
        public static string HtmlIDDelimitador {
            get {
                return ResourceManager.GetString("HtmlIDDelimitador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_ddlDelimitadores.
        /// </summary>
        public static string HtmlIDDelimitadores {
            get {
                return ResourceManager.GetString("HtmlIDDelimitadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_optEncabezadoSi.
        /// </summary>
        public static string HtmlIDEncabezadoSi {
            get {
                return ResourceManager.GetString("HtmlIDEncabezadoSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblCodigoError.
        /// </summary>
        public static string HtmlIDErrorCode {
            get {
                return ResourceManager.GetString("HtmlIDErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblMensaje.
        /// </summary>
        public static string HtmlIDErrorMessage {
            get {
                return ResourceManager.GetString("HtmlIDErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_dtFechaDesde.
        /// </summary>
        public static string HtmlIDFechaDesde {
            get {
                return ResourceManager.GetString("HtmlIDFechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_dtFechaHasta.
        /// </summary>
        public static string HtmlIDFechaHasta {
            get {
                return ResourceManager.GetString("HtmlIDFechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bAceptar.
        /// </summary>
        public static string HtmlIDLoginAceptar {
            get {
                return ResourceManager.GetString("HtmlIDLoginAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtClave.
        /// </summary>
        public static string HtmlIDLoginClave {
            get {
                return ResourceManager.GetString("HtmlIDLoginClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtUsuario.
        /// </summary>
        public static string HtmlIDLoginUsuario {
            get {
                return ResourceManager.GetString("HtmlIDLoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_optParametros.
        /// </summary>
        public static string HtmlIDParametros {
            get {
                return ResourceManager.GetString("HtmlIDParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_optExcel.
        /// </summary>
        public static string HtmlIDRadioExcel {
            get {
                return ResourceManager.GetString("HtmlIDRadioExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_cp_rdbRango.
        /// </summary>
        public static string HtmlIDRadioRango {
            get {
                return ResourceManager.GetString("HtmlIDRadioRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_btnSalir_lnkButton.
        /// </summary>
        public static string HtmlIDSalir {
            get {
                return ResourceManager.GetString("HtmlIDSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00$cp$ctl25.
        /// </summary>
        public static string HtmlNameInput {
            get {
                return ResourceManager.GetString("HtmlNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string NavigateAccount {
            get {
                return ResourceManager.GetString("NavigateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPasswordBFI.
        /// </summary>
        public static string SettingsLoginPasswordBFI {
            get {
                return ResourceManager.GetString("SettingsLoginPasswordBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPasswordTD.
        /// </summary>
        public static string SettingsLoginPasswordTD {
            get {
                return ResourceManager.GetString("SettingsLoginPasswordTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUserBFI.
        /// </summary>
        public static string SettingsLoginUserBFI {
            get {
                return ResourceManager.GetString("SettingsLoginUserBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUserTD.
        /// </summary>
        public static string SettingsLoginUserBFITD {
            get {
                return ResourceManager.GetString("SettingsLoginUserBFITD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/WebSiteBc/ConsultaMovimientosCuenta/MovimientosCuenta.aspx.
        /// </summary>
        public static string URLAccount {
            get {
                return ResourceManager.GetString("URLAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/WebSiteBc/default.aspx.
        /// </summary>
        public static string URLDefault {
            get {
                return ResourceManager.GetString("URLDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/CAU/Comunes/Error.aspx?P=1.
        /// </summary>
        public static string URLError {
            get {
                return ResourceManager.GetString("URLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/CAU/Comunes/Error.aspx.
        /// </summary>
        public static string URLError2 {
            get {
                return ResourceManager.GetString("URLError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/WebSiteBc/ConsultaMovimientosCuenta/Exportar.aspx.
        /// </summary>
        public static string URLExportar {
            get {
                return ResourceManager.GetString("URLExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/CAU/inicio/inicio.aspx?svc=mantis&amp;Banco=01.
        /// </summary>
        public static string URLLogin {
            get {
                return ResourceManager.GetString("URLLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/MANTIS/WEBSITE/login.aspx.
        /// </summary>
        public static string URLLoginAlternate {
            get {
                return ResourceManager.GetString("URLLoginAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.banesconline.com/mantis/WebSiteBc/salir.aspx.
        /// </summary>
        public static string URLSalir {
            get {
                return ResourceManager.GetString("URLSalir", resourceCulture);
            }
        }
    }
}
