//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Service.Reconciliator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReconciliatorServiceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReconciliatorServiceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Service.Reconciliator.ReconciliatorServiceErrors", typeof(ReconciliatorServiceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-RS-001.
        /// </summary>
        public static string MultiplePossibleEntriesExceptionCode {
            get {
                return ResourceManager.GetString("MultiplePossibleEntriesExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen múltiples movimientos posibles a conciliar para la declaración pendiente. Solo es posible asociar un movimiento a una declaración específica..
        /// </summary>
        public static string MultiplePossibleEntriesExceptionMessage {
            get {
                return ResourceManager.GetString("MultiplePossibleEntriesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-RS-000.
        /// </summary>
        public static string ReconciliatorErrorCode {
            get {
                return ResourceManager.GetString("ReconciliatorErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el servicio de conciliación automática.
        /// </summary>
        public static string ReconciliatorErrorMessage {
            get {
                return ResourceManager.GetString("ReconciliatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-RS-002.
        /// </summary>
        public static string StatementAmountExceptionCode {
            get {
                return ResourceManager.GetString("StatementAmountExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto declarado difiere del monto en cuenta.
        /// </summary>
        public static string StatementAmountExceptionMessage {
            get {
                return ResourceManager.GetString("StatementAmountExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-RS-003.
        /// </summary>
        public static string StatementDeclaredExceptionCode {
            get {
                return ResourceManager.GetString("StatementDeclaredExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El movimiento ya ha posee una declaracion asociada.
        /// </summary>
        public static string StatementDeclaredExceptionMessage {
            get {
                return ResourceManager.GetString("StatementDeclaredExceptionMessage", resourceCulture);
            }
        }
    }
}
