//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Scraper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScraperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScraperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Scraper.ScraperResources", typeof(ScraperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFI.
        /// </summary>
        public static string AccountOptionBFI {
            get {
                return ResourceManager.GetString("AccountOptionBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transdestino.
        /// </summary>
        public static string AccountOptionTD {
            get {
                return ResourceManager.GetString("AccountOptionTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banesco.
        /// </summary>
        public static string BankOptionBanesco {
            get {
                return ResourceManager.GetString("BankOptionBanesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincial.
        /// </summary>
        public static string BankOptionProvincial {
            get {
                return ResourceManager.GetString("BankOptionProvincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CharDash {
            get {
                return ResourceManager.GetString("CharDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string CharSlash {
            get {
                return ResourceManager.GetString("CharSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CMNBack {
            get {
                return ResourceManager.GetString("CMNBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string CMNForward {
            get {
                return ResourceManager.GetString("CMNForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string CMNReload {
            get {
                return ResourceManager.GetString("CMNReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstaTransfer.ScraperPresenter.Fonts.fontawesome-webfont.ttf.
        /// </summary>
        public static string CustomFontPath {
            get {
                return ResourceManager.GetString("CustomFontPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd--HH-mm-ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser.
        /// </summary>
        public static string DictionaryKeyBrowser {
            get {
                return ResourceManager.GetString("DictionaryKeyBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string DictionaryKeyPassword {
            get {
                return ResourceManager.GetString("DictionaryKeyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rif.
        /// </summary>
        public static string DictionaryKeyRIF {
            get {
                return ResourceManager.GetString("DictionaryKeyRIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string DictionaryKeyUser {
            get {
                return ResourceManager.GetString("DictionaryKeyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        public static string DoubleBackslash {
            get {
                return ResourceManager.GetString("DoubleBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        public static string FileExtensionCsv {
            get {
                return ResourceManager.GetString("FileExtensionCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xls.
        /// </summary>
        public static string FileExtensionExcel {
            get {
                return ResourceManager.GetString("FileExtensionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string HtmlAttributeSelected {
            get {
                return ResourceManager.GetString("HtmlAttributeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string HtmlAttributeValue {
            get {
                return ResourceManager.GetString("HtmlAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-right.
        /// </summary>
        public static string HtmlIDContentRight {
            get {
                return ResourceManager.GetString("HtmlIDContentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string HtmlMemberClick {
            get {
                return ResourceManager.GetString("HtmlMemberClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onChange.
        /// </summary>
        public static string HtmlOnChangeEvent {
            get {
                return ResourceManager.GetString("HtmlOnChangeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onclick.
        /// </summary>
        public static string HtmlOnclickEvent {
            get {
                return ResourceManager.GetString("HtmlOnclickEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        public static string HtmlTagInput {
            get {
                return ResourceManager.GetString("HtmlTagInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string HtmlTagLink {
            get {
                return ResourceManager.GetString("HtmlTagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string MIMETypeExcel {
            get {
                return ResourceManager.GetString("MIMETypeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.text.
        /// </summary>
        public static string MIMETypeText {
            get {
                return ResourceManager.GetString("MIMETypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Explorer.
        /// </summary>
        public static string PageTitleDefault {
            get {
                return ResourceManager.GetString("PageTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiddler.certmaker.bc.cert.
        /// </summary>
        public static string PrefFiddlerCert {
            get {
                return ResourceManager.GetString("PrefFiddlerCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiddler.certmaker.bc.key.
        /// </summary>
        public static string PrefFiddlerPK {
            get {
                return ResourceManager.GetString("PrefFiddlerPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string RequestMethodPost {
            get {
                return ResourceManager.GetString("RequestMethodPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScraperView.
        /// </summary>
        public static string ScraperProcessName {
            get {
                return ResourceManager.GetString("ScraperProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings.
        /// </summary>
        public static string SectonAppSettings {
            get {
                return ResourceManager.GetString("SectonAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCertificate.
        /// </summary>
        public static string SettingsFiddlerCert {
            get {
                return ResourceManager.GetString("SettingsFiddlerCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPrimaryKey.
        /// </summary>
        public static string SettingsFiddlerPK {
            get {
                return ResourceManager.GetString("SettingsFiddlerPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPassword.
        /// </summary>
        public static string SettingsLoginPassword {
            get {
                return ResourceManager.GetString("SettingsLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUser.
        /// </summary>
        public static string SettingsLoginUser {
            get {
                return ResourceManager.GetString("SettingsLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string ShortDateFormat {
            get {
                return ResourceManager.GetString("ShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFI.
        /// </summary>
        public static string ToggleAccountOptionBFI {
            get {
                return ResourceManager.GetString("ToggleAccountOptionBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        public static string ToggleAccountOptionTD {
            get {
                return ResourceManager.GetString("ToggleAccountOptionTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string ToggleDateOptionDay {
            get {
                return ResourceManager.GetString("ToggleDateOptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ToggleDateOptionRange {
            get {
                return ResourceManager.GetString("ToggleDateOptionRange", resourceCulture);
            }
        }
    }
}
