//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.BackEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackEndErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackEndErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.BackEnd.BackEndErrors", typeof(BackEndErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-000.
        /// </summary>
        public static string BackEndErrorCode {
            get {
                return ResourceManager.GetString("BackEndErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación Fallida.
        /// </summary>
        public static string BackEndErrorMessage {
            get {
                return ResourceManager.GetString("BackEndErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-002.
        /// </summary>
        public static string CashOutRequestAnnullErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestAnnullErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al anular la solicitud de retiro.
        /// </summary>
        public static string CashOutRequestAnnullErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestAnnullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-004.
        /// </summary>
        public static string CashOutRequestApproveErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestApproveErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al aprobar la solicitud.
        /// </summary>
        public static string CashOutRequestApproveErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestApproveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-005.
        /// </summary>
        public static string CashOutRequestCompleteErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestCompleteErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al completar la solicitud de retiro.
        /// </summary>
        public static string CashOutRequestCompleteErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestCompleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-001.
        /// </summary>
        public static string CashOutRequestCreateErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestCreateErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la solicitud de retiro.
        /// </summary>
        public static string CashOutRequestCreateErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-000.
        /// </summary>
        public static string CashOutRequestErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la solicitud de retiro.
        /// </summary>
        public static string CashOutRequestErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-CO-003.
        /// </summary>
        public static string CashOutRequestRejectErrorCode {
            get {
                return ResourceManager.GetString("CashOutRequestRejectErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al rechazar la solicitud de retiro.
        /// </summary>
        public static string CashOutRequestRejectErrorMessage {
            get {
                return ResourceManager.GetString("CashOutRequestRejectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-001.
        /// </summary>
        public static string CommerceModificationExceptionCode {
            get {
                return ResourceManager.GetString("CommerceModificationExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la mofificacion de los datos del comercio.
        /// </summary>
        public static string CommerceModificationExceptionMessage {
            get {
                return ResourceManager.GetString("CommerceModificationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-D-001.
        /// </summary>
        public static string DeclarationAmountExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationAmountExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la declaracion y la orden de compra no coinciden.
        /// </summary>
        public static string DeclarationAmountExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationAmountExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-002.
        /// </summary>
        public static string DeclarationAnnulledExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationAnnulledExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración esta anulada.
        /// </summary>
        public static string DeclarationAnnulledExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationAnnulledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-D-000.
        /// </summary>
        public static string DeclarationErrorCode {
            get {
                return ResourceManager.GetString("DeclarationErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la declaración del pago.
        /// </summary>
        public static string DeclarationErrorMessage {
            get {
                return ResourceManager.GetString("DeclarationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-D-007.
        /// </summary>
        public static string DeclarationNotFoundExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationNotFoundExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la declaracion asociada.
        /// </summary>
        public static string DeclarationNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-D-002.
        /// </summary>
        public static string DeclarationPaymentUserExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationPaymentUserExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del pagador de la declaracion no coinciden con los registrados en la orden de compra.
        /// </summary>
        public static string DeclarationPaymentUserExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationPaymentUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-003.
        /// </summary>
        public static string DeclarationReconciledExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationReconciledExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración esta conciliada.
        /// </summary>
        public static string DeclarationReconciledExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationReconciledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-D-003.
        /// </summary>
        public static string DuplicateReferenceExceptionCode {
            get {
                return ResourceManager.GetString("DuplicateReferenceExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numero de referencia ya se encuentra registrado.
        /// </summary>
        public static string DuplicateReferenceExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateReferenceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-006.
        /// </summary>
        public static string InsufficientFundsErrorCode {
            get {
                return ResourceManager.GetString("InsufficientFundsErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos Insuficientes.
        /// </summary>
        public static string InsufficientFundsErrorMessage {
            get {
                return ResourceManager.GetString("InsufficientFundsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-006.
        /// </summary>
        public static string InvalidUserExceptionCode {
            get {
                return ResourceManager.GetString("InvalidUserExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Inválido.
        /// </summary>
        public static string InvalidUserExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-005.
        /// </summary>
        public static string PaymentRequestAnnulledExceptionCode {
            get {
                return ResourceManager.GetString("PaymentRequestAnnulledExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud ya se encuentra anulada.
        /// </summary>
        public static string PaymentRequestAnnulledExceptionMessage {
            get {
                return ResourceManager.GetString("PaymentRequestAnnulledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-000.
        /// </summary>
        public static string PaymentRequestErrorCode {
            get {
                return ResourceManager.GetString("PaymentRequestErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la solicitud de pago.
        /// </summary>
        public static string PaymentRequestErrorMessage {
            get {
                return ResourceManager.GetString("PaymentRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-004.
        /// </summary>
        public static string PaymentRequestNotAssociatedExceptionCode {
            get {
                return ResourceManager.GetString("PaymentRequestNotAssociatedExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de pago no asociada al usuario actual.
        /// </summary>
        public static string PaymentRequestNotAssociatedExceptionMessage {
            get {
                return ResourceManager.GetString("PaymentRequestNotAssociatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-001.
        /// </summary>
        public static string PaymentRequestNotFoundExceptionCode {
            get {
                return ResourceManager.GetString("PaymentRequestNotFoundExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la solicitud de pago asociada.
        /// </summary>
        public static string PaymentRequestNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PaymentRequestNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-002.
        /// </summary>
        public static string PaymentRequestProcessedExceptionCode {
            get {
                return ResourceManager.GetString("PaymentRequestProcessedExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta solicitud ya ha sido procesada.
        /// </summary>
        public static string PaymentRequestProcessedExceptionMessage {
            get {
                return ResourceManager.GetString("PaymentRequestProcessedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PR-003.
        /// </summary>
        public static string PaymentRequestSendErrorCode {
            get {
                return ResourceManager.GetString("PaymentRequestSendErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al enviar la solicitud.
        /// </summary>
        public static string PaymentRequestSendErrorMessage {
            get {
                return ResourceManager.GetString("PaymentRequestSendErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PO-005.
        /// </summary>
        public static string PurchaseOrderAnnulledExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulledExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra esta anulada.
        /// </summary>
        public static string PurchaseOrderAnnulledExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PO-001.
        /// </summary>
        public static string PurchaseOrderAnnulmentExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulmentExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al anular la orden de compra.
        /// </summary>
        public static string PurchaseOrderAnnulmentExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulmentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PO-004.
        /// </summary>
        public static string PurchaseOrderDeclarationExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclarationExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al anular la declaracion asociada a la orden de compra.
        /// </summary>
        public static string PurchaseOrderDeclarationExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclarationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PO-003.
        /// </summary>
        public static string PurchaseOrderDeclaredExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclaredExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra ya se encuentra declarada.
        /// </summary>
        public static string PurchaseOrderDeclaredExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclaredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-BE-PO-002.
        /// </summary>
        public static string PurchaseOrderNotFoundExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderNotFoundExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la orden de compra asociada.
        /// </summary>
        public static string PurchaseOrderNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderNotFoundExceptionMessage", resourceCulture);
            }
        }
    }
}
