//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.BackEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackEndResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackEndResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.BackEnd.BackEndResources", typeof(BackEndResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración no pudo ser anulada.
        /// </summary>
        public static string AnnulDeclarationFail {
            get {
                return ResourceManager.GetString("AnnulDeclarationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración ha sido anulada.
        /// </summary>
        public static string AnnulDeclarationSuccess {
            get {
                return ResourceManager.GetString("AnnulDeclarationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden no pudo ser anulada.
        /// </summary>
        public static string AnnulOrderFail {
            get {
                return ResourceManager.GetString("AnnulOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden ha sido anulada.
        /// </summary>
        public static string AnnulOrderSuccess {
            get {
                return ResourceManager.GetString("AnnulOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de pago no pudo ser anulada.
        /// </summary>
        public static string AnnulPaymentRequestFail {
            get {
                return ResourceManager.GetString("AnnulPaymentRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de pago ha sido anulada.
        /// </summary>
        public static string AnnulPaymentRequestSuccess {
            get {
                return ResourceManager.GetString("AnnulPaymentRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA.
        /// </summary>
        public static string AppSettingsKeyIVA {
            get {
                return ResourceManager.GetString("AppSettingsKeyIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWTExpirationMinutes.
        /// </summary>
        public static string AppSettingsKeyJWTExpiration {
            get {
                return ResourceManager.GetString("AppSettingsKeyJWTExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinCashOut.
        /// </summary>
        public static string AppSettingsKeyMinCashOut {
            get {
                return ResourceManager.GetString("AppSettingsKeyMinCashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRequestUrl.
        /// </summary>
        public static string AppSettingsKeyPaymentRequestUrl {
            get {
                return ResourceManager.GetString("AppSettingsKeyPaymentRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoTransax.
        /// </summary>
        public static string AppSettingsKeyTransaxInfoMail {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxInfoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoReplyTransax.
        /// </summary>
        public static string AppSettingsKeyTransaxNoReplyMail {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxNoReplyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTransax.
        /// </summary>
        public static string AppSettingsKeyTransaxSupportMail {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxSupportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransaxUrl.
        /// </summary>
        public static string AppSettingsKeyTransaxUrl {
            get {
                return ResourceManager.GetString("AppSettingsKeyTransaxUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion exitosa.
        /// </summary>
        public static string BackEndSuccessMessage {
            get {
                return ResourceManager.GetString("BackEndSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro ha sido anulada.
        /// </summary>
        public static string CashOutRequestAnnullSuccessMessage {
            get {
                return ResourceManager.GetString("CashOutRequestAnnullSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro ha sido aprobada.
        /// </summary>
        public static string CashOutRequestApproveSuccessMessage {
            get {
                return ResourceManager.GetString("CashOutRequestApproveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro ha sido aprobada.
        /// </summary>
        public static string CashOutRequestCompleteSuccessMessage {
            get {
                return ResourceManager.GetString("CashOutRequestCompleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro no pudo ser procesada.
        /// </summary>
        public static string CashOutRequestFail {
            get {
                return ResourceManager.GetString("CashOutRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro ha sido rechazada.
        /// </summary>
        public static string CashOutRequestRejectSuccessMessage {
            get {
                return ResourceManager.GetString("CashOutRequestRejectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud de retiro ha sido procesada.
        /// </summary>
        public static string CashOutRequestSuccess {
            get {
                return ResourceManager.GetString("CashOutRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commercestatus.
        /// </summary>
        public static string CommerceStatusClaim {
            get {
                return ResourceManager.GetString("CommerceStatusClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado exitosamente.
        /// </summary>
        public static string CreateCUserSuccessMessage {
            get {
                return ResourceManager.GetString("CreateCUserSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuser.
        /// </summary>
        public static string CUserClaim {
            get {
                return ResourceManager.GetString("CUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cusertestmode.
        /// </summary>
        public static string CUserTestModeClaim {
            get {
                return ResourceManager.GetString("CUserTestModeClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaracion exitosa.
        /// </summary>
        public static string DeclarationSuccessMessage {
            get {
                return ResourceManager.GetString("DeclarationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago procesado.
        /// </summary>
        public static string EndUserDeclarationReconciledSuccess {
            get {
                return ResourceManager.GetString("EndUserDeclarationReconciledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago pendiente por procesar.
        /// </summary>
        public static string EndUserDeclarationSuccess {
            get {
                return ResourceManager.GetString("EndUserDeclarationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Listado de Avances.
        /// </summary>
        public static string FilenameTableAdvance {
            get {
                return ResourceManager.GetString("FilenameTableAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Retiros en Cuenta.
        /// </summary>
        public static string FilenameTableCashouts {
            get {
                return ResourceManager.GetString("FilenameTableCashouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Declaraciones.
        /// </summary>
        public static string FilenameTableDeclarations {
            get {
                return ResourceManager.GetString("FilenameTableDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Ordenes de Compra.
        /// </summary>
        public static string FilenameTableOrders {
            get {
                return ResourceManager.GetString("FilenameTableOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Solicitudes de Pago.
        /// </summary>
        public static string FilenameTableRequests {
            get {
                return ResourceManager.GetString("FilenameTableRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Movimientos Bancarios.
        /// </summary>
        public static string FilenameTableStatement {
            get {
                return ResourceManager.GetString("FilenameTableStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transax Usuarios.
        /// </summary>
        public static string FilenameTableUsers {
            get {
                return ResourceManager.GetString("FilenameTableUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión exitoso.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion exitosa.
        /// </summary>
        public static string OperationSuccessMessage {
            get {
                return ResourceManager.GetString("OperationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud ha sido enviada.
        /// </summary>
        public static string PaymentRequestSuccess {
            get {
                return ResourceManager.GetString("PaymentRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de orden de compra exitosa.
        /// </summary>
        public static string PurchaseOrderSuccessMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración no pudo ser conciliada.
        /// </summary>
        public static string ReconcileDeclarationFail {
            get {
                return ResourceManager.GetString("ReconcileDeclarationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración ha sido conciliada.
        /// </summary>
        public static string ReconcileDeclarationSuccess {
            get {
                return ResourceManager.GetString("ReconcileDeclarationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rif.
        /// </summary>
        public static string RifClaim {
            get {
                return ResourceManager.GetString("RifClaim", resourceCulture);
            }
        }
    }
}
