//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaTransfer.ITResources.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaTransfer.ITResources.Api.ApiErrors", typeof(ApiErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-012.
        /// </summary>
        public static string DeclarationAmountExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationAmountExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la declaracion y la orden de compra no coinciden.
        /// </summary>
        public static string DeclarationAmountExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationAmountExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-009.
        /// </summary>
        public static string DeclarationErrorCode {
            get {
                return ResourceManager.GetString("DeclarationErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaracion fallida.
        /// </summary>
        public static string DeclarationErrorMessage {
            get {
                return ResourceManager.GetString("DeclarationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-010.
        /// </summary>
        public static string DeclarationNotFoundErrorCode {
            get {
                return ResourceManager.GetString("DeclarationNotFoundErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaracion no encontrada.
        /// </summary>
        public static string DeclarationNotFoundMessage {
            get {
                return ResourceManager.GetString("DeclarationNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-013.
        /// </summary>
        public static string DeclarationPaymentUserExceptionCode {
            get {
                return ResourceManager.GetString("DeclarationPaymentUserExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del pagador de la declaracion no coinciden con los registrados en la orden de compra.
        /// </summary>
        public static string DeclarationPaymentUserExceptionMessage {
            get {
                return ResourceManager.GetString("DeclarationPaymentUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-008.
        /// </summary>
        public static string DeclarationValidationErrorCode {
            get {
                return ResourceManager.GetString("DeclarationValidationErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la validacion de los datos de la declaracion.
        /// </summary>
        public static string DeclarationValidationErrorMessage {
            get {
                return ResourceManager.GetString("DeclarationValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-002.
        /// </summary>
        public static string DuplicateReferenceExceptionCode {
            get {
                return ResourceManager.GetString("DuplicateReferenceExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numero de referencia ya se encuentra registrado.
        /// </summary>
        public static string DuplicateReferenceExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateReferenceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-015.
        /// </summary>
        public static string InactiveUserExceptionCode {
            get {
                return ResourceManager.GetString("InactiveUserExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ingresar un usuario inactivo..
        /// </summary>
        public static string InactiveUserExceptionMessage {
            get {
                return ResourceManager.GetString("InactiveUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-001.
        /// </summary>
        public static string InvalidUserExceptionCode {
            get {
                return ResourceManager.GetString("InvalidUserExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inválido.
        /// </summary>
        public static string InvalidUserExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-014.
        /// </summary>
        public static string InvalidUserRoleExceptionCode {
            get {
                return ResourceManager.GetString("InvalidUserRoleExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol del usuario del comercio invalido.
        /// </summary>
        public static string InvalidUserRoleExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidUserRoleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-016.
        /// </summary>
        public static string InvalidUserTestModeExceptionCode {
            get {
                return ResourceManager.GetString("InvalidUserTestModeExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio inactivo, no puede acceder con este usuario.
        /// </summary>
        public static string InvalidUserTestModeExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidUserTestModeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-000.
        /// </summary>
        public static string OperationErrorCode {
            get {
                return ResourceManager.GetString("OperationErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion fallida.
        /// </summary>
        public static string OperationErrorMessage {
            get {
                return ResourceManager.GetString("OperationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-007.
        /// </summary>
        public static string ParametersRequiredErrorCode {
            get {
                return ResourceManager.GetString("ParametersRequiredErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros requeridos.
        /// </summary>
        public static string ParametersRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ParametersRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-014.
        /// </summary>
        public static string PurchaseOrderAnnulledExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulledExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra se encuentra anulada.
        /// </summary>
        public static string PurchaseOrderAnnulledExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderAnnulledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-005.
        /// </summary>
        public static string PurchaseOrderCreateErrorCode {
            get {
                return ResourceManager.GetString("PurchaseOrderCreateErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la orden de compra.
        /// </summary>
        public static string PurchaseOrderCreateErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-004.
        /// </summary>
        public static string PurchaseOrderDeclaredExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclaredExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra ya se encuentra declarada.
        /// </summary>
        public static string PurchaseOrderDeclaredExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderDeclaredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-011.
        /// </summary>
        public static string PurchaseOrderErrorCode {
            get {
                return ResourceManager.GetString("PurchaseOrderErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de compra invalida.
        /// </summary>
        public static string PurchaseOrderErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-003.
        /// </summary>
        public static string PurchaseOrderNotFoundExceptionCode {
            get {
                return ResourceManager.GetString("PurchaseOrderNotFoundExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la orden de compra asociada.
        /// </summary>
        public static string PurchaseOrderNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-006.
        /// </summary>
        public static string PurchaseOrderValidationErrorCode {
            get {
                return ResourceManager.GetString("PurchaseOrderValidationErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la validacion de los datos de la orden.
        /// </summary>
        public static string PurchaseOrderValidationErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseOrderValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-API-017.
        /// </summary>
        public static string SignatureVerificationExceptionCode {
            get {
                return ResourceManager.GetString("SignatureVerificationExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al verificar el token.
        /// </summary>
        public static string SignatureVerificationExceptionMessage {
            get {
                return ResourceManager.GetString("SignatureVerificationExceptionMessage", resourceCulture);
            }
        }
    }
}
